#!/bin/bash
set -e

# chmod a+x autoscript_BWC.sh
# Create a directory containing the reference file
# Use "cat input.file" and pipe (|) into this script

# Define the date variable
DATE="$(date +"%Y%m%d_%k%M%S")"
# Define the current working directory
myDIR="$(pwd -P)"
# Define the trimming sequence
trimSEQ="$1"
# Define the reference file name
refFILE="reference.fa"
# Define the reference sequence name
refNAME="reference"
# Define output filename
output="001_BWC_BLACK_PCR.fastq"

if [ "${trimSEQ}" = "1" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACATCACGATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"
elif [ "${trimSEQ}" = "2" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCGATGTATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"	
elif [ "${trimSEQ}" = "3" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACTTAGGCATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"	
elif [ "${trimSEQ}" = "4" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACTGACCAATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"	
elif [ "${trimSEQ}" = "5" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACACAGTGATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"	
elif [ "${trimSEQ}" = "6" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"	
elif [ "${trimSEQ}" = "7" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCAGATCATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"	
elif [ "${trimSEQ}" = "8" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACACTTGAATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"	
elif [ "${trimSEQ}" = "9" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGATCAGATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"	
elif [ "${trimSEQ}" = "10" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACTAGCTTATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"	
elif [ "${trimSEQ}" = "11" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGGCTACATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"	
elif [ "${trimSEQ}" = "12" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCTTGTAATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"	
elif [ "${trimSEQ}" = "13" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACAGTCAACAATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"	
elif [ "${trimSEQ}" = "14" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACAGTTCCGTATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"	
elif [ "${trimSEQ}" = "15" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACATGTCAGAATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"	
elif [ "${trimSEQ}" = "16" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCCGTCCCGATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"	
elif [ "${trimSEQ}" = "18" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGTCCGCACATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"	
elif [ "${trimSEQ}" = "19" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGTGAAACGATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"	
elif [ "${trimSEQ}" = "20" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGTGGCCTTATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"	
elif [ "${trimSEQ}" = "21" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGTTTCGGAATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"	
elif [ "${trimSEQ}" = "22" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCGTACGTAATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"	
elif [ "${trimSEQ}" = "23" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGAGTGGATATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"	
elif [ "${trimSEQ}" = "25" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACACTGATATATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"	
elif [ "${trimSEQ}" = "27" ]; then
	adapter="AGATCGGAAGAGCACACGTCTGAACTCCAGTCACATTCCTTTATCTCGTATGCCGTCTTCTGCTTG"
	echo "$adapter"	
fi


	fastx_clipper -Q 33 -v -a "${adapter}" -l 100 | \
	fastq_quality_filter -Q 33 -v -q 30 -p 75 | \
	awk 'BEGIN {OFS = "\n"} {header = $0 ; getline seq ; getline qheader ; getline qseq ; if (length(seq) == 112) {print header, seq, qheader, qseq}}' \
	> temp_"${output}"

	echo "Reads left after filtered for length:"
	wc -l temp_"${output}" | xargs -n 1 | \
	sed -n 1p | while read number; do echo $((number / 4)); done

	java -jar /Users/Gordon/prog/ShortRefGlobalAligner/ShortRefGlobalAligner.jar \
	-f temp_"${output}" -r "${myDIR}"/reference/"${refFILE}" -n "${refNAME}" > "${output}".txt
	rm temp_"${output}"


# List of Truseq adapter indexes (with added 5' A as from the A tailing step)
# >TruSeq_Adapter_Index_1
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACATCACGATCTCGTATGCCGTCTTCTGCTTG
# >TruSeq_Adapter_Index_2
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCGATGTATCTCGTATGCCGTCTTCTGCTTG
# >TruSeq_Adapter_Index_3
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACTTAGGCATCTCGTATGCCGTCTTCTGCTTG
# >TruSeq_Adapter_Index_4
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACTGACCAATCTCGTATGCCGTCTTCTGCTTG
# >TruSeq_Adapter_Index_5
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACACAGTGATCTCGTATGCCGTCTTCTGCTTG
# >TruSeq_Adapter_Index_6
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTGCTTG
# >TruSeq_Adapter_Index_7
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCAGATCATCTCGTATGCCGTCTTCTGCTTG
# >TruSeq_Adapter_Index_8
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACACTTGAATCTCGTATGCCGTCTTCTGCTTG
# >TruSeq_Adapter_Index_9
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGATCAGATCTCGTATGCCGTCTTCTGCTTG
# >TruSeq_Adapter_Index_10
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACTAGCTTATCTCGTATGCCGTCTTCTGCTTG
# >TruSeq_Adapter_Index_11
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGGCTACATCTCGTATGCCGTCTTCTGCTTG
# >TruSeq_Adapter_Index_12
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCTTGTAATCTCGTATGCCGTCTTCTGCTTG
# >TruSeq_Adapter_Index_13
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACAGTCAACAATCTCGTATGCCGTCTTCTGCTTG
# >TruSeq_Adapter_Index_14
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACAGTTCCGTATCTCGTATGCCGTCTTCTGCTTG
# >TruSeq_Adapter_Index_15
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACATGTCAGAATCTCGTATGCCGTCTTCTGCTTG
# >TruSeq_Adapter_Index_16
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCCGTCCCGATCTCGTATGCCGTCTTCTGCTTG
# >TruSeq_Adapter_Index_18_7
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGTCCGCACATCTCGTATGCCGTCTTCTGCTTG
# >TruSeq_Adapter_Index_19
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGTGAAACGATCTCGTATGCCGTCTTCTGCTTG
# >TruSeq_Adapter_Index_20
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGTGGCCTTATCTCGTATGCCGTCTTCTGCTTG
# >TruSeq_Adapter_Index_21
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGTTTCGGAATCTCGTATGCCGTCTTCTGCTTG
# >TruSeq_Adapter_Index_22
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCGTACGTAATCTCGTATGCCGTCTTCTGCTTG
# >TruSeq_Adapter_Index_23
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGAGTGGATATCTCGTATGCCGTCTTCTGCTTG
# >TruSeq_Adapter_Index_25
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACACTGATATATCTCGTATGCCGTCTTCTGCTTG
# >TruSeq_Adapter_Index_27
# AGATCGGAAGAGCACACGTCTGAACTCCAGTCACATTCCTTTATCTCGTATGCCGTCTTCTGCTTG